user_set = set()
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)
user_input = int(input('Enter a number '))
user_set.add(user_input)

print(user_set)